apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bar
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: 738947182016.dkr.ecr.eu-central-1.amazonaws.com/bar:latest
        ports:
        - containerPort: 80
        env:
          - name: "PORT"
            value: "80"
