---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bar
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: image_url/bar:latest
        ports:
        - containerPort: 80
        env:
          - name: "PORT"
            value: "80"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: image_url/bar:latest
        ports:
        - containerPort: 81
        env:
          - name: "PORT"
            value: "81"
