---
apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: bar

---
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: foo
